# Generated by Django 2.2.4 on 2021-05-28 11:11

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('semiapp', '0002_auto_20210525_1709'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tv',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
