# Generated by Django 2.2.4 on 2021-05-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semiapp', '0003_auto_20210528_1411'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tv',
            managers=[
            ],
        ),
    ]
